services:
  conduit:
    image: 'ghcr.io/hariso/custom-conduit:v0.7.0'
    container_name: conduit
    volumes:
      - './pipelines/mongo-to-kafka.yaml:/app/pipelines/p.yaml'
      # - '../example_records/conduit-opencdc-json-record.json:/app/record.json'
    ports:
      - '8081:8080'
    networks:
      - benchi

networks:
  benchi:
    external: true
