version: "2.2"
pipelines:
    - id: generator-to-kafka
      status: stopped
      name: ""
      description: Generator to Kafka
      connectors:
        - id: generator-source
          type: source
          plugin: generator
          settings:
            # global settings
            # rate: 14000
            recordCount: 2000000
            # default collection
            format.type: file
            format.options.path: "/app/record.json"
            operations: create
            sdk.schema.extract.key.enabled: false
            sdk.schema.extract.payload.enabled: false
        - id: kafka-destination
          type: destination
          plugin: builtin:kafka
          name: kafka-destination
          settings:
            servers: "broker:29092"
            topic: destination-topic
            sdk.batch.size: 10000
            sdk.batch.delay: "1s"
            sdk.schema.extract.key.enabled: false
            sdk.schema.extract.payload.enabled: false
