services:
  conduit:
    # https://github.com/hariso/conduit-mongo-connect
    image: 'ghcr.io/hariso/custom-conduit:v0.5.0'
    container_name: conduit
#    depends_on:
#      broker:
#        condition: service_healthy
#      mongo-init:
#        condition: service_completed_successfully  # Ensure it only starts after DB is ready
    volumes:
      - './conduit-pipelines/mongo-to-kafka.yaml:/app/pipelines/mongo-to-kafka.yaml'
    ports:
      - '8081:8080'
    networks:
      - benchi

networks:
  benchi:
    external: true
