version: "2.2"
pipelines:
    - id: mongo-to-file-again
      status: running
      name: ""
      description: MongoDB to file
      connectors:
        - id: mongo-source
          type: source
          plugin: builtin:mongo
          settings:
            collection: users
            db: test
            uri: "mongodb://mongo1:30001,mongo2:30002,mongo3:30003/test?replicaSet=my-replica-set"
            sdk.schema.extract.key.enabled: false
            sdk.schema.extract.payload.enabled: false
        - id: kafka-destination
          type: destination
          plugin: builtin:kafka
          name: kafka-destination
          settings:
            servers: "broker:29092"
            topic: destination-topic
            compression: "none"
            # batch size in Kafka Connect is 16kb, messages are around 800b
            # which results in about 20 messages per batch.
            sdk.batch.size: 10000
            sdk.batch.delay: "1s"
            sdk.record.format: "opencdc/json"
            sdk.record.format.options: "position.excluded=true"
