services:
  mongo1:
    image: 'mongo:5'
    container_name: mongo1
    command:
      - '--replSet'
      - my-replica-set
      - '--bind_ip_all'
      - '--port'
      - '30001'
    volumes:
      - './data/mongo-1:/data/db'
    ports:
      - '30001:30001'
    healthcheck:
      test: 'test $$(echo "rs.initiate({_id:''my-replica-set'',members:[{_id:0,host:\"mongo1:30001\"},{_id:1,host:\"mongo2:30002\"},{_id:2,host:\"mongo3:30003\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1'
      interval: 10s
      start_period: 30s
    networks:
      - benchi
  
  mongo2:
    image: 'mongo:5'
    container_name: mongo2
    command:
      - '--replSet'
      - my-replica-set
      - '--bind_ip_all'
      - '--port'
      - '30002'
    volumes:
      - './data/mongo-2:/data/db'
    ports:
      - '30002:30002'
    networks:
      - benchi
  
  mongo3:
    image: 'mongo:5'
    container_name: mongo3
    command:
      - '--replSet'
      - my-replica-set
      - '--bind_ip_all'
      - '--port'
      - '30003'
    volumes:
      - './data/mongo-3:/data/db'
    ports:
      - '30003:30003'
    networks:
      - benchi

  mongo-init:
    image: 'mongo:5'
    container_name: mongo-init
    restart: "no"
    depends_on:
      mongo1:
        condition: service_healthy
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
    entrypoint: ["mongosh", "--host", "mongo1:30001", "/docker-entrypoint-initdb.d/init-db.js"]
    networks:
      - benchi

  broker:
    image: confluentinc/cp-server:7.8.1
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      # health checks happen every 2s, failures in the first 30s are not counted toward the maximum number of retries,
      # after 5 failed health checks the service is marked as unhealthy
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_DURABILITY_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:9092
      CONFLUENT_METRICS_TOPIC_REPLICAS: 1
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - benchi

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.8.1
    hostname: control-center
    container_name: control-center
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - benchi

networks:
  benchi:
    external: true
